= Smilee

This repository contains the source code for the v2 of Smilee.

== Dependencies

* link:https://github.com/dverso/foundry-env[Foundry environment]

== Installation

You have to create and fill a `.env` file from the `.env.template` one.

== Deployment

=== Local testnet

. `make chain`
. `make shell`
. `source .env`
. `forge script script/testnet/01_CoreFoundations.s.sol:DeployCoreFoundations --fork-url $RPC_LOCALNET --broadcast -vvvv`
. `forge script script/testnet/02_Token.s.sol:DeployToken --fork-url $RPC_LOCALNET --broadcast -vvvv --sig 'deployToken(string memory)' <SYMBOL>`
. `forge script script/testnet/02_Token.s.sol:DeployToken --fork-url $RPC_LOCALNET --broadcast -vvvv --sig 'setTokenPrice(address,uint256)' <TOKEN_ADDRESS> <TOKEN_PRICE>`
. `forge script script/testnet/03_Factory.s.sol:DeployDVP --fork-url $RPC_LOCALNET --broadcast -vvvv --sig 'createIGMarket(address,address,uint256)' <BASE_TOKEN_ADDRESS> <SIDE_TOKEN_ADDRESS> <INT_OF_FREQUENCY>`
. `forge script script/testnet/04_Epoch.s.sol:RollEpoch --fork-url $RPC_LOCALNET --broadcast -vvvv`
. `exit`
