= Smilee

This repository contains the source code for the v2 of Smilee.

== Dependencies

* link:https://github.com/dverso/foundry-env[Foundry environment]

== Installation

You have to create and fill a `.env` file from the `.env.template` one.

== Deployment

=== Local testnet

. `make chain`
. `make shell`
. `source .env`
. Deploy core contracts, libraries and base token:
+
`forge script script/testnet/01_CoreFoundations.s.sol:DeployCoreFoundations --fork-url $RPC_LOCALNET --broadcast -vvvv`
. Deploy a new `<SYMBOL>` token (e.g. "ETH" for "sETH"):
+
`forge script script/testnet/02_Token.s.sol:DeployToken --fork-url $RPC_LOCALNET --broadcast -vvvv --sig 'deployToken(string memory)' <SYMBOL>`
. Set a token price.:
+
`forge script script/testnet/02_Token.s.sol:DeployToken --fork-url $RPC_LOCALNET --broadcast -vvvv --sig 'setTokenPrice(address,uint256)' <TOKEN_ADDRESS> <TOKEN_PRICE>`
. Create an Impermanent Gain DVP and its Vault:
+
`forge script script/testnet/03_Factory.s.sol:DeployDVP --fork-url $RPC_LOCALNET --broadcast -vvvv --sig 'createIGMarket(address,address,uint256)' <BASE_TOKEN_ADDRESS> <SIDE_TOKEN_ADDRESS> <INT_OF_FREQUENCY>`
. Roll the epoch for every DVP/Vault that need it:
+
`forge script script/testnet/04_Epoch.s.sol:RollEpoch --fork-url $RPC_LOCALNET --broadcast -vvvv`
. Mint and deposit the given `<AMOUNT>` of base tokens into the provided vault:
+
`forge script script/testnet/05_Vault.s.sol:VaultOps --fork-url $RPC_LOCALNET --broadcast -vvvv --sig 'fillVault(address,uint256)' <VAULT_ADDRESS> <AMOUNT>`
. Advance chain time:
+
`cast rpc --rpc-url $RPC_LOCALNET evm_increaseTime <SECONDS> && cast rpc --rpc-url $RPC_LOCALNET evm_mine`
. `exit`
